<a href="https://colab.research.google.com/github/gauravgupta5813-coder/SMS-Spam-classifier/blob/main/Spam_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded_files = files.upload()

Saving spam.csv to spam.csv

In [3]:
df = pd.read_csv("spam.csv", encoding="latin-1")
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [4]:
if 'v1' in df.columns and 'v2' in df.columns:
    df = df[['v1', 'v2']]
    # rename columns
    df.columns = ['label', 'message']
elif 'label' in df.columns and 'message' in df.columns:
    # If columns are already renamed, do nothing or re-display head
    pass
else:
    # Handle unexpected column names if neither original nor renamed exist
    print("DataFrame does not contain expected columns ('v1', 'v2' or 'label', 'message').")

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

df.head()

/tmp/ipykernel_1159/1757753585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = df['label'].map({

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [6]:
df['label'].value_counts()

label
0    4825
1     747
Name: count, dtype: int64

In [7]:
df['message'] = df['message'].str.lower()
df.head()

/tmp/ipykernel_1159/648580707.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['message'] = df['message'].str.lower()

   label                                            message
0      0  go until jurong point, crazy.. available only ...
1      0                      ok lar... joking wif u oni...
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0  u dun say so early hor... u c already then say...
4      0  nah i don't think he goes to usf, he lives aro...

In [8]:
import string

In [9]:
df['message'] = df['message'].astype(str).apply(lambda x : x.translate(str.maketrans('', '', string.punctuation)))
df.head()

/tmp/ipykernel_1159/4235254685.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['message'] = df['message'].astype(str).apply(lambda x : x.translate(str.maketrans('', '', string.punctuation)))

   label                                            message
0      0  go until jurong point crazy available only in ...
1      0                            ok lar joking wif u oni
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0        u dun say so early hor u c already then say
4      0  nah i dont think he goes to usf he lives aroun...

In [10]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [11]:
df['message'] = df['message'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopwords.words('english'))]))
df.head()

/tmp/ipykernel_1159/764736047.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['message'] = df['message'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopwords.words('english'))]))

   label                                            message
0      0  go jurong point crazy available bugis n great ...
1      0                            ok lar joking wif u oni
2      1  free entry 2 wkly comp win fa cup final tkts 2...
3      0                u dun say early hor u c already say
4      0        nah dont think goes usf lives around though

In [12]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

# Apply stemming to each message in the 'message' column
df['message'] = df['message'].apply(lambda text: ' '.join([ps.stem(word) for word in text.split()]))
df.head()

/tmp/ipykernel_1159/2726213584.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['message'] = df['message'].apply(lambda text: ' '.join([ps.stem(word) for word in text.split()]))

   label                                            message
0      0  go jurong point crazi avail bugi n great world...
1      0                              ok lar joke wif u oni
2      1  free entri 2 wkli comp win fa cup final tkt 21...
3      0                u dun say earli hor u c alreadi say
4      0          nah dont think goe usf live around though

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X = df['message']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)

X_test = vectorizer.transform(X_test)

In [17]:
# Print the shape of the TF-IDF matrix for the training data
print(f"Shape of X_train TF-IDF matrix: {X_train.shape}")

# The shape tells us: (number of documents, number of unique words/features)

Shape of X_train TF-IDF matrix: (4457, 7113)

In [18]:
# Get feature names (words) from the vectorizer
feature_names = vectorizer.get_feature_names_out()

# Display a few feature names
print("\nFirst 20 feature names (words):")
print(feature_names[:20])

First 20 feature names (words):
['008704050406' '0089mi' '0121' '01223585236' '0125698789' '02' '020603'
 '0207' '02070836089' '02072069400' '02073162414' '02085076972' '020903'
 '021' '050703' '0578' '06' '061104' '07046744435' '07090201529']

To see the actual numerical values, let's look at the TF-IDF scores for the first message and the corresponding words. We'll convert the first row of the sparse matrix to a dense array and then map it back to the words.

In [19]:
# Get the TF-IDF scores for the first message in the training set
# Use X_train[0] because the vectorizer and feature_names were derived from the training data.
first_message_tfidf = X_train[0].toarray()

# Create a pandas Series for easier viewing of word-score pairs
# feature_names should correspond to the columns of X_train
word_scores = pd.Series(first_message_tfidf[0], index=feature_names)

# Display the words with their non-zero TF-IDF scores for the first message
print("\nTF-IDF scores for the first message (non-zero values only):")
display(word_scores[word_scores > 0].sort_values(ascending=False))

TF-IDF scores for the first message (non-zero values only):

boat     0.430163
nake     0.430163
im       0.383208
mom      0.352518
half     0.323859
yo       0.322039
check    0.300281
still    0.245030
dtype: float64

In [20]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)
y_train_smote.value_counts()

label
0    3860
1    3860
Name: count, dtype: int64

In [21]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

model.fit(X_train_smote, y_train_smote)

MultinomialNB()

In [22]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [23]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9668161434977578

In [24]:
y_pred[:10]

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [25]:
y_test[:10].values

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [26]:
msg = ["Your Amazon order has been delivered"]
msg_vector = vectorizer.transform(msg)

prediction = model.predict(msg_vector)

print(prediction)

[0]

In [27]:
if prediction[0] == 1:
    print("Spam")
else:
    print("Not Spam")

Not Spam